version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - task -d ../token build || exit 1
      - soroban contract build --no-default-features --features=tokens_2
      - soroban contract optimize --wasm target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract.wasm --wasm-out target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract_2_tokens.wasm
      - soroban contract build --no-default-features --features=tokens_3
      - soroban contract optimize --wasm target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract.wasm --wasm-out target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract_3_tokens.wasm
      - soroban contract build --no-default-features --features=tokens_4
      - soroban contract optimize --wasm target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract.wasm --wasm-out target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract_4_tokens.wasm
      - ls -l target/wasm32-unknown-unknown/release/*.wasm

  test:
    deps:
      - build
    cmds:
      - cargo test --no-default-features --features=tokens_2
      - cargo test --no-default-features --features=tokens_3
      - cargo test --no-default-features --features=tokens_4

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
