version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - soroban contract build --features=tokens_2
      - mv target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract.wasm target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract_2_tokens.wasm
      - soroban contract build --features=tokens_3
      - mv target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract.wasm target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract_3_tokens.wasm
      - soroban contract build --features=tokens_4
      - mv target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract.wasm target/wasm32-unknown-unknown/release/soroban_liquidity_pool_stableswap_contract_4_tokens.wasm
      - ls -l target/wasm32-unknown-unknown/release/*.wasm

  test:
    deps:
      - build
    cmds:
      - cargo test --features=tokens_2 -- --nocapture
      - cargo test --features=tokens_3 -- --nocapture
      - cargo test --features=tokens_4 -- --nocapture

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
