repos:
  - repo: local
    hooks:
      - id: fmt
        name: fmt all
        description: Format files with cargo fmt.
        entry: task fmt
        language: system
        types: [ rust ]
        args: [ "--" ]
