version: '3'

env:
  SUBDIRS:
    sh: dirname $(find . -mindepth 2 -maxdepth 3 -type f -name Taskfile.yaml)

tasks:
  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: test

  build:
    cmds:
      - task -d liquidity_pool_router build || exit 1
      - task -d liquidity_pool_provider_swap_fee build || exit 1
      - task -d liquidity_pool_provider_swap_fee_factory build || exit 1
      - task -d fees_collector build || exit 1
      - cp ./target/wasm32-unknown-unknown/release/*.wasm ./contracts

  test:
    cmds:
      - for: { var: SUBDIRS }
        cmd: task -d {{ .ITEM }} test || exit 1

  test_slow:
    cmds:
      - for: { var: SUBDIRS }
        cmd: task -d {{ .ITEM }} test_slow || exit 1

  fmt:
    cmds:
      - for: { var: SUBDIRS }
        cmd: task -d {{ .ITEM }} fmt || exit 1

  clean:
    cmds:
      - for: { var: SUBDIRS }
        cmd: task -d {{ .ITEM }} clean || exit 1

  _check_bindings_tranfer_ownership:
    vars:
      WASMS:
        sh: find ./target/wasm32-unknown-unknown/release/ -maxdepth 1 -type f \( -name '*.wasm' -and -not -name 'soroban_liquidity_pool_provider_swap_fee_contract.wasm' \)
    cmds:
      - for: { var: WASMS }
        cmd:
          echo "Checking bindings for {{ .ITEM }}" &&
          soroban contract info interface --wasm {{ .ITEM }} | grep commit_transfer_ownership && 
          soroban contract info interface --wasm {{ .ITEM }} | grep apply_transfer_ownership
          || exit 1

  _check_bindings_delayed_upgrade:
    vars:
      WASMS:
        sh: find ./target/wasm32-unknown-unknown/release/ -maxdepth 1 -type f \( -name '*.wasm' -and -not -name 'soroban_token_contract.wasm' -and -not -name 'soroban_liquidity_pool_provider_swap_fee_contract.wasm' \)
    cmds:
      - for: { var: WASMS }
        cmd:
          echo "Checking bindings for {{ .ITEM }}" &&
          soroban contract info interface --wasm {{ .ITEM }} | grep apply_upgrade && 
          soroban contract info interface --wasm {{ .ITEM }} | grep commit_upgrade 
          || exit 1

  _check_bindings_upgrade:
    vars:
      WASM: "./target/wasm32-unknown-unknown/release/soroban_token_contract.wasm"
    cmds:
      - echo "Checking upgrade bindings for {{ .WASM }}" && 
        soroban contract info interface --wasm {{ .WASM }} | grep upgrade 
        || exit 1

  check_bindings:
    cmds:
      - task build
      - task _check_bindings_tranfer_ownership
      - task _check_bindings_delayed_upgrade
      - task _check_bindings_upgrade
