pub const DAY_IN_LEDGERS: u32 = 17280;
pub const WEEK_IN_LEDGERS: u32 = DAY_IN_LEDGERS * 7;
pub const MONTH_IN_LEDGERS: u32 = DAY_IN_LEDGERS * 30;

// Temporary TTL
pub const MAX_TEMPORARY_TTL: u32 = WEEK_IN_LEDGERS;
pub const TEMPORARY_TTL_THRESHOLD: u32 = MAX_TEMPORARY_TTL - DAY_IN_LEDGERS;
