version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - soroban contract build --package soroban_config_storage_contract
      - soroban contract optimize --wasm ../target/wasm32v1-none/release/soroban_config_storage_contract.wasm --wasm-out ../target/wasm32v1-none/release/soroban_config_storage_contract.wasm
      - ls -l ../target/wasm32v1-none/release/*.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
