version: '3'
tasks:
  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check

  build:
    cmds:
      - stellar contract build --package soroban-liquidity-pool-plane-contract
      - stellar contract optimize --wasm ../target/wasm32v1-none/release/soroban_liquidity_pool_plane_contract.wasm --wasm-out ../contracts/soroban_liquidity_pool_plane_contract.wasm
      - ls -l ../contracts/*.wasm

  test:
    deps:
      - build
    cmd: cargo test

  test_slow:
    cmds:
      - task: test

  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: check
      - task: test
